# Generated by Django 2.2.6 on 2019-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileToDedupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_xlsx', models.FileField(upload_to='%Y-%m-%d/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_processed', models.DateTimeField(blank=True, db_index=True, default=None, editable=False)),
            ],
        ),
    ]
