# Generated by Django 2.2.6 on 2019-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='UploadedFile',
            name='date_processed',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
