# Generated by Django 2.2.6 on 2019-10-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0002_auto_20191007_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name_plural': 'uploaded files'},
        ),
    ]
